##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.

# setup DATETIME on Linux as: 
#   export DATETIME=`date "+%Y-%m-%d_%H:%M"`
#   export lbCommand=update
#   export lbCommandArgs="""
#   export targetSchema="${schema}"

globalVariables:
  CONTAINER: asmith-s3-extension-demo
  CHECK_DRIFT: "false"

stages:
  Validation:
    actions: 
      - type: shell
        command: echo "command=$lbCommand and schema=$schema and targetSchema=$targetSchema and args=$lbCommandArgs"

  eachSchema:
    actions:
    
      - type: shell
        command: echo "Switching to ${schema}" && cd ${schema} && pwd

      - type: liquibase
        if: "${CHECK_DRIFT} == true"
        globalArgs: { defaultsFile: "${schema}/liquibase.properties", reports-name: "drift-report-${schema}.html" }
        command: diff
        cmdArgs: { reference-url: "offline:mssql?snapshot=${schema}-snapshot.json", drift-severity: 1, schemas: "${schema}" }

      - type: liquibase
        if: "${lbCommand} == update"
        globalArgs: { defaultsFile: "${schema}/liquibase.properties", reports-name: "checks-report-${schema}-changelog.html" }
        command: checks run
        cmdArgs: {checks-scope: changelog, changeset-filter: PENDING}

      - type: liquibase
        if: "${lbCommand} == update"
        globalArgs: { defaultsFile: "${schema}/liquibase.properties" }
        command: status
        cmdArgs: {verbose: true}

      - type: liquibase
        if: "${lbCommand} == update"
        globalArgs: { defaultsFile: "${schema}/liquibase.properties", reports-name: "update-sql-report-${schema}.html" }
        command: update-sql

      - type: liquibase
        if: "${lbCommand} == update"
        globalArgs: { defaultsFile: "${schema}/liquibase.properties", reports-name: "update-report-${schema}.html" }
        command: update

      - type: liquibase
        if: "${lbCommand} == rollbackOneUpdate"
        globalArgs: { defaultsFile: "${schema}/liquibase.properties", reports-name: "rollback-report-${schema}.html" }
        command: rollback-one-update
        cmdArgs: {force: true}

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: snapshot
      cmdArgs: {  snapshot-format: json, schemas: "${schema}" }
      globalArgs: { output-file: 's3://${CONTAINER}/oracleSnapshots/${schema}-snapshot.json',  defaultsFile: "${schema}/liquibase.properties"}
        
    - type: shell
      command: echo 'Updated snapshot saved to s3://${CONTAINER}/oracleSnapshots/${schema}-snapshot.json'  
  
    - type: liquibase
      globalArgs: { defaultsFile: "${schema}/liquibase.properties" }
      command: history