##########           LIQUIBASE MULTI-SCHEMA FLOWFILE                ##########

globalVariables:
  SCHEMAS: ${LB_SCHEMAS}
  FLOWFILE: "update.flowfile.yaml"   
  
stages:          
  Call-Liquibase:
    actions:
      - type: shell
        command: |
            echo ${SCHEMAS}
            bash -c 'IFS=,; for SCHEMA_NAME in $1; do echo "### Deploying to ${SCHEMA_NAME} ###"; liquibase connect --url="jdbc:oracle:thin:@cs-oracledb.liquibase.net:1521/CAPS_TEST1" --username="liquibase_user" --password="liquibase_user"; done' bash "${SCHEMAS}"

  Call-Liquibase2:
    actions:
      - type: shell
        command: |
            echo ${SCHEMAS}
            bash -c 'IFS=,; for SCHEMA_NAME in $1; do echo "### Deploying to ${SCHEMA_NAME} ###"; liquibase connect --url="jdbc:oracle:thin:@cs-oracledb.liquibase.net:1521/CAPS_TEST1" --username="${SCHEMA_NAME}" --password="${SCHEMA_NAME}"; done' bash "${SCHEMAS}"